chore: update config

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,13 +45,13 @@ jobs:
           if [ ! -d "$HOME/.ssh" ]; then
             mkdir -p "$HOME/.ssh"
           fi
-          ssh-keyscan -H ec2-51-20-136-79.eu-north-1.compute.amazonaws.com >> "$HOME/.ssh/known_hosts" || echo "ssh-keyscan failed, continuing"
+          ssh-keyscan -H ec2-56-228-5-25.eu-north-1.compute.amazonaws.com >> "$HOME/.ssh/known_hosts" || echo "ssh-keyscan failed, continuing"
 
       - name: Deploy with PM2
         env:
           NODE_ENV: production
         run: |
-          SSH_HOST="ec2-51-20-136-79.eu-north-1.compute.amazonaws.com"
+          SSH_HOST="ec2-56-228-5-25.eu-north-1.compute.amazonaws.com"
 
           ssh -i login-key.pem \
             -o StrictHostKeyChecking=no \
